### ISSUE TITLE
Just an Error (wsfield)

### ISSUE THREAD

**Issue by lquessenberry** [spotzero/wsdata#12]
Error: Call to a member function call() on null in Drupal\wsdata\WSDataService->call() (line 29 of /var/www/my_project/web/modules/contrib/wsdata/src/WSDataService.php) #0 /var/www/my_project/web/modules/contrib/wsdata/modules/wsdata_field/wsdata_field.module(71): Drupal\wsdata\WSDataService->call(NULL, NULL, Array, '', Array, 'videos:0:video_...', Array) #1 /var/www/my_project/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(301): wsdata_field_entity_load(Array, 'node') #2 /var/www/my_project/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(249): Drupal\Core\Entity\EntityStorageBase->postLoad(Array) #3 /var/www/my_project/web/core/modules/views/src/Plugin/views/query/Sql.php(1563): Drupal\Core\Entity\EntityStorageBase->loadMultiple(Array) #4 /var/www/my_project/web/core/modules/views/src/Plugin/views/query/Sql.php(1488): Drupal\views\Plugin\views\query\Sql->loadEntities(Array) #5 /var/www/my_project/web/core/modules/views/src/ViewExecutable.php(1423): Drupal\views\Plugin\views\query\Sql->execute(Object(Drupal\views\ViewExecutable)) #6 /var/www/my_project/web/core/modules/views/src/ViewExecutable.php(1451): Drupal\views\ViewExecutable->execute(NULL) #7 /var/www/my_project/web/core/modules/views/src/Plugin/views/display/Page.php(171): Drupal\views\ViewExecutable->render() #8 /var/www/my_project/web/core/modules/views/src/ViewExecutable.php(1627): Drupal\views\Plugin\views\display\Page->execute() #9 /var/www/my_project/web/core/modules/views/src/Element/View.php(77): Drupal\views\ViewExecutable->executeDisplay('page_1', Array) #10 [internal function]: Drupal\views\Element\View::preRenderViewElement(Array) #11 /var/www/my_project/web/core/lib/Drupal/Core/Render/Renderer.php(378): call_user_func(Array, Array) #12 /var/www/my_project/web/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false) #13 /var/www/my_project/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(226): Drupal\Core\Render\Renderer->render(Array, false) #14 /var/www/my_project/web/core/lib/Drupal/Core/Render/Renderer.php(576): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() #15 /var/www/my_project/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(227): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #16 /var/www/my_project/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(117): Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch)) #17 /var/www/my_project/web/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch)) #18 /var/www/my_project/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(108): Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher)) #19 /var/www/my_project/vendor/symfony/http-kernel/HttpKernel.php(158): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent)) #20 /var/www/my_project/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #21 /var/www/my_project/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #22 /var/www/my_project/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #23 /var/www/my_project/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #24 /var/www/my_project/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #25 /var/www/my_project/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #26 /var/www/my_project/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(50): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #27 /var/www/my_project/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #28 /var/www/my_project/web/core/lib/Drupal/Core/DrupalKernel.php(657): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #29 /var/www/my_project/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #30 {main}.

**Comment by morinluc0** [comment]
Looking at this error I can see why its being caused but not sure why.

The first parameter to the call should be the wscall name and its NULL. I wonder if there is some configurations that are stuck and its causing this error.

Drupal\wsdata\WSDataService->call(NULL, NULL, Array, '', Array, 'videos:0:video_...', Array)
